# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Article.delete_all
User.delete_all
Comment.delete_all

user1 = User.create!(username: "demo", email: "gmail.com", password: "123456")

Article.create(user_id: user1.id, title: "Winners and Losers of the NBA Trade Deadline",
body: "Winner: Cleveland Cavaliers
The Cavs’ front office deserves a ton of credit for its creativity and courage in overhauling the roster. As The Ringer’s Jonathan Tjarks detailed, the three prominent guards they dealt — Isaiah Thomas, Derrick Rose, and Dwyane Wade — were part of the problem defensively, while the additions — Rodney Hood, George Hill, and Jordan Clarkson — should all help on that end. Larry Nance Jr. is an upgrade over Tristan Thompson, and though the Cavs lost Jae Crowder, they already have Jeff Green, who has been better than Crowder. Rookie Cedi Osman is also ready for a more significant role. All of the NBA execs I talked to after the deadline thought this team got better on paper. The Cavaliers play only three games over the next 13 days, giving coach Tyronn Lue and the staff plenty of time to integrate the new blood and prepare the team to reintegrate Kevin Love once he returns from his broken left hand. There are no guarantees it’ll work. If Hood, Hill, Clarkson, and Nance are supposed to save your season, you’re asking for a bit much. Hood and Hill are also injury prone, but they’re still better than what the Cavs had. These deals are also wins for future seasons, too. Though the Cavaliers gave up their own first-round pick in the deal with the Lakers for Clarkson and Nance, they retained the coveted 2018 Nets first-round pick. So they still have the ability to add either a high-end prospect in a talented lottery class, or deal the pick if the right opportunity comes their way in June. They also added players who can be part of their core in the years ahead, with or without LeBron James. Clarkson, Nance, and Hood are all 25. Osman, who joined the team over the summer, is 22. If LeBron stays, that’s swell. But if he leaves, Cleveland won’t be left with one of the most hopeless rosters in basketball, as it was the last time LeBron left and was prepared to be again. Instead, the Cavaliers have finally started to build a roster with an eye toward the future.
Winner: Los Angeles Lakers
There were rumblings hours before the deadline that the Lakers were using Nance as a sweetener to dump Clarkson, who is owed nearly $26 million over the next two seasons. But the Cavs stepped up and it all worked out perfectly for the Lakers — they got a first-round pick and the expiring contracts of Isaiah Thomas and Channing Frye. The Lakers now have only $34.6 million in guaranteed salaries this upcoming offseason, when James and Paul George can become unrestricted free agents. There is still more work to be done, including stretching Luol Deng’s albatross contract, but the front-office team of Rob Pelinka and Magic Johnson cleared the way toward cap space for two max free agents.
Loser: Rob Pelinka
Pelinka and Johnson were asked whether they had substantive conversations that would’ve allowed them to deal Deng. Magic chuckled, flashed his billion-dollar smile, turned to Pelinka and cracked, “We wish, huh?” Pelinka was screaming internally.
Losers: Ex-Lottery Picks (and Their Teams)
Not only was Elfrid Payton, the no. 10 overall pick in 2014, dealt for a second-round pick, but the Nuggets traded Emmanuel Mudiay, drafted seventh in 2015, in a three-way trade for 34-year-old point guard Devin Harris. The Kings also flat-out cut Georgios Papagiannis, the no. 13 pick in 2016. The Magic regime that selected Payton is gone, and the Kings’ front office has been overhauled, but it’s typically never a good sign when a player is being cut loose before the end of his rookie contract.
Winner: Detroit Pistons
The Pistons shocked the basketball world by trading for Blake Griffin on January 29, and then they made some quiet yet quality additions on Thursday. They first acquired veteran point guard Jameer Nelson, who can fortify the bench, and later snatched swingman James Ennis from the Grizzlies for big man Brice Johnson and a second-rounder. Nelson and Ennis aren’t exactly big-time acquisitions, but the Pistons are going all in, and every bit helps.
Winner: Phoenix Suns
The Suns entered the trade deadline three years ago with a trio of point guards: Goran Dragic, Isaiah Thomas, and Eric Bledsoe. All three are gone now, and with Brandon Knight still missing in action, Tyler Ulis still short, and Isaiah Canaan sidelined, Phoenix’s point guard cupboard is completely depleted. Now they have Payton. I know what you’re thinking: “But Payton wasn’t good in Orlando.” That’s true, but he’s played for four coaches over four seasons. Look at former teammate Victor Oladipo, who found his way with the Pacers at age 25. Sometimes all it takes is time and the right situation. Payton probably won’t blossom like Oladipo, who made his first All-Star team this season, but there’s no risk here for the Suns. They gave up only a second-rounder from their endless pile of them, which is a cheap price to pay for a point guard who turns 24 later this month and has shown flashes over his time with the Magic. The Suns haven’t exactly been a model of stability, either. But for two months, Payton will get an opportunity to show what he can do next to Devin Booker and Josh Jackson. Payton’s solid playmaking and defense can at least be useful off the bench. If the restricted-free-agent-to-be shows he can be the long-term starter, there will be less of a need to draft a point guard like Trae Young or Collin Sexton, meaning the Suns can divert their attention to others in this year’s loaded draft class.
", cover_img_url: "https://cdn.vox-cdn.com/thumbor/j7HcYPMe2pGKMEJlclsx8TfQFqc=/0x0:3000x2000/920x613/filters:focal(1209x480:1689x960):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/58631541/KOC_trade_dealine_winners_losers_getty_ringer.0.jpg")

Article.create(user_id: user1.id, title: "Are high US healthcare costs just an illusion?" , body: "Readers of American Nations often ask if something changed with regard to the regional cultures to allow the 2016 Republican nominee, Donald Trump, to capture the Electoral College votes of several key “blue” and swing states and, thus, the White House.

The answer, which initially surprises many, is no. Voting behaviors among the 11 “nations” I identify in the book actually corresponded to what one would have expected. The critical difference wasn’t that some regional cultures had suddenly become “more conservative” or “less liberal,” whatever those terms are supposed to mean these days. What changed was the political program offered by the Republican nominee, who promised the most communitarian-minded agenda of any such nominee in the past four decades. His complete reversal of those promises will likely allow Democrats to roll back his gains in the very places that proved decisive last time around.
Here’s what happened in 2016, as seen through the lens of America’s regional cultures, which, as I’ve previously demonstrated in this series, have more influence on electoral outcomes than the differences between rural and urban life or between the states, whose borders were often drawn with little thought to actual settlement history and cultural fissures. (If you’re new to this paradigm, you can find a summary here.)
First, the top-line results: Just as one would expect, the more communitarian-minded candidate—Hillary Clinton, in this election—won Left Coast, New Netherland, and Yankeedom by wide margins. Like her Democratic predecessor, Clinton also had a wide margin of victory in Tidewater and El Norte, two onetime swing regions that have, for differing reasons, become reliable members of the “blue” coalition over the past 15 years. She also captured the southernmost part of Florida, which is part of a wider Spanish Caribbean regional culture that (like Hawaii and Newfoundland) is not treated in American Nations. In almost all of these “nations,” Clinton actually matched or outperformed Barack Obama’s 2012 results.", cover_img_url: "https://www.statnews.com/wp-content/uploads/2017/12/Blockchain-healthcare-graphic-645x645.png")


Article.create(user_id: user1.id, title: "The Coming Software Apocalypse",
body: "The 911 outage, at the time the largest ever reported, was traced to software running on a server in Englewood, Colorado. Operated by a systems provider named Intrado, the server kept a running counter of how many calls it had routed to 911 dispatchers around the country. Intrado programmers had set a threshold for how high the counter could go. They picked a number in the millions.
Shortly before midnight on April 10, the counter exceeded that number, resulting in chaos. Because the counter was used to generate a unique identifier for each call, new calls were rejected. And because the programmers hadn’t anticipated the problem, they hadn’t created alarms to call attention to it. Nobody knew what was happening. Dispatch centers in Washington, California, Florida, the Carolinas, and Minnesota, serving 11 million Americans, struggled to make sense of reports that callers were getting busy signals. It took until morning to realize that Intrado’s software in Englewood was responsible, and that the fix was to change a single number.
Not long ago, emergency calls were handled locally. Outages were small and easily diagnosed and fixed. The rise of cellphones and the promise of new capabilities—what if you could text 911? or send videos to the dispatcher?—drove the development of a more complex system that relied on the internet. For the first time, there could be such a thing as a national 911 outage. There have now been four in as many years.
It’s been said that software is “eating the world.” More and more, critical systems that were once controlled mechanically, or by people, are coming to depend on code. This was perhaps never clearer than in the summer of 2015, when on a single day, United Airlines grounded its fleet because of a problem with its departure-management system; trading was suspended on the New York Stock Exchange after an upgrade; the front page of The Wall Street Journal’s website crashed; and Seattle’s 911 system went down again, this time because a different router failed. The simultaneous failure of so many software systems smelled at first of a coordinated cyberattack. Almost more frightening was the realization, late in the day, that it was just a coincidence.
“When we had electromechanical systems, we used to be able to test them exhaustively,” says Nancy Leveson, a professor of aeronautics and astronautics at the Massachusetts Institute of Technology who has been studying software safety for 35 years. She became known for her report on the Therac-25, a radiation-therapy machine that killed six patients because of a software error. “We used to be able to think through all the things it could do, all the states it could get into.” The electromechanical interlockings that controlled train movements at railroad crossings, for instance, only had so many configurations; a few sheets of paper could describe the whole system, and you could run physical trains against each configuration to see how it would behave. Once you’d built and tested it, you knew exactly what you were dealing with.
Software is different. Just by editing the text in a file somewhere, the same hunk of silicon can become an autopilot or an inventory-control system. This flexibility is software’s miracle, and its curse. Because it can be changed cheaply, software is constantly changed; and because it’s unmoored from anything physical—a program that is a thousand times more complex than another takes up the same actual space—it tends to grow without bound. “The problem,” Leveson wrote in a book, “is that we are attempting to build systems that are beyond our ability to intellectually manage.”", cover_img_url: "https://i.pinimg.com/originals/b2/ca/39/b2ca392174bf598fd4f7af51f7e70dc1.jpg")

Article.create(user_id: user1.id, title: 'Fear not, China is not banning cryptocurrency', body: "In 2008 following the financial crisis, a paper titled “Bitcoin: A Peer-to-Peer Electronic Cash System” was published, detailing the concepts of a payment system. Bitcoin was born. Bitcoin gained the attention of the world for its use of blockchain technology and as an alternative to fiat currencies and commodities. Dubbed the next best technology after the internet, blockchain offered solutions to issues we have failed to address, or ignored over the past few decades. I will not delve into the technical aspect of it but here are some articles and videos that I recommend:

How Bitcoin Works Under the Hood
Fast forward to today, 5th February to be exact, authorities in China have just unveiled a new set of regulations to ban cryptocurrency. The Chinese government have already done so last year, but many have circumvented through foreign exchanges. It has now enlisted the almighty ‘Great Firewall of China’ to block access to foreign exchanges in a bid to stop its citizens from carrying out any cryptocurrency transactions.
To know more about the Chinese government stance, let’s backtrack a couple years back to 2013 when Bitcoin was gaining popularity among the Chinese citizens and prices were soaring. Concerned with the price volatility and speculations, the People’s Bank of China and five other government ministries published an official notice on December 2013 titled “Notice on Preventing Financial Risk of Bitcoin” (Link is in Mandarin). Several points were highlighted:
1. Due to various factors such as limited supply, anonymity and lack of a centralized issuer, Bitcoin is not a official currency but a virtual commodity that cannot be used in the open market.
2. All banks and financial organizations are not allowed to offer Bitcoin-related financial services or engage in trading activity related to Bitcoin.
3. All companies and websites that offer Bitcoin-related services are to register with the necessary government ministries.
4. Due to the anonymity and cross-border features of Bitcoin, organizations providing Bitcoin-related services ought to implement preventive measures such as KYC to prevent money laundering. Any suspicious activity including fraud, gambling and money laundering should to be reported to the authorities.
5.Organizations providing Bitcoin-related services ought to educate the public about Bitcoin and the technology behind it and not mislead the public with misinformation.
In layman’s term, Bitcoin is categorized as a virtual commodity (e.g in-game credits,) that can be bought or sold in its original form and not to be exchanged with fiat currency. It cannot be defined as money- something that serves as a medium of exchange, a unit of accounting, and a store of value.
Despite the notice being dated in 2013, it is still relevant with regards to the Chinese government stance on Bitcoin and as mentioned, there is no indication of the banning Bitcoin and cryptocurrency. Rather, regulation and education about Bitcoin and blockchain will play a role in the Chinese crypto-market.
A similar notice was issued on Jan 2017, again emphasizing that Bitcoin is a virtual commodity and not a currency. In September 2017, the boom of initial coin offerings (ICOs) led to the publishing of a separate notice titled “Notice on Preventing Financial Risk of Issued Tokens”. Soon after, ICOs were banned and Chinese exchanges were investigated and eventually closed. (Hindsight is 20/20, they have made the right decision to ban ICOs and stop senseless gambling). Another blow was dealt to China’s cryptocurrency community in January 2018 when mining operations faced serious crackdowns, citing excessive electricity consumption." , cover_img_url: "https://blog.giantswarm.io/assets/2015/04/Wikimedia_Servers-small.jpg")

Article.create(user_id: user1.id, title: "What Investors Really Fear",
body: "The Dow Jones Industrial Average has fallen by 1,000 points only twice in its 122-year history. The first time was Monday. The second was Thursday.
There are two points to make about this. First, stocks have had a miserable week. The Dow erased nearly $3 trillion in wealth with a 10 percent plunge that officially qualifies as what’s called a market “correction.”
Second, stocks have had a marvelous decade. The Dow has thousands of points to lose because it has accumulated thousands of points in the last few years, quadrupling since 2009. With this latest collapse, the index of 30 stocks has fallen way, way back to levels not glimpsed since the dystopian hellscape of … Thanksgiving 2017.
So, what’s this all about? The stock market is a synthesis of stories about the future, a global anthology of investors’ financial predictions. When stocks rise steadily with little volatility—as they have for the last few years—it suggests widespread agreement on the world’s economic narrative. For a long time, the story went that corporate profits were rising in global unison for the first time in years, as both inflation and interest rates stayed low, creating a relatively risk-free environment for equities.
Then, rather suddenly, the story changed. On Friday of last week, the Bureau of Labor Statistics announced that wages had grown by 2.9 percent over the previous 12 months, a record high for the current expansion. This seems to have triggered fears that higher wages chasing a finite number of goods and services would lead to higher prices and furthermore that higher prices would encourage the Federal Reserve to raise interest rates to combat inflation.
Just as low interest rates had buoyed stock prices for years, the fear of rising interest rates has the opposite effect, inspiring a “flight to safety” as traders switch from stocks to fixed-income investments, such as government bonds. As investors scrambled to move money from equities to bonds, many traders who had bet against this sort of volatility—through a (now controversial) financial instrument, called XIV, that essentially allowed people to place wagers on continued calmness in the markets—were nearly wiped out. It all led to the worst nominal loss in the history of the Dow.
And that was just Monday. On Tuesday and Wednesday, stocks whirled like a plastic bag in a hurricane, at one point recovering most of their losses. Then, on Thursday, everything fell apart all over again in the midst of a crowded news cycle, as China’s trade surplus narrowed, and Republicans announced their plan to pass a deficit-swelling budget.
The significance of this week’s market gyrations can be stated simply: There is no reason to believe that this is the beginning a global financial crisis. Nor is there reason to believe this is the foreshadowing of a U.S. recession. Assigning monocausal blame for soaring or plunging stocks is a rough business, but what happened this week is in all likelihood a tizzy over inflation.
But if markets are afraid of inflation, they are fearing a ghost. Ever since the 2008 financial crisis, warnings of incipient inflation have been both persistent and wrong. The Federal Reserve has routinely aimed for 2 percent inflation in the years following the housing crash, and its aim has been routinely low. In 2016 and 2017, wage growth accelerated for lower-income Americans. But annual growth in “core personal-consumption expenditures”—the Fed’s most commonly used inflation measure—was 1.7 and 1.5 percent in those years. Wages perked up a bit. Prices didn’t.
If investors are afraid of the Fed’s approach to inflation, it is ironic that this season’s research note from the Federal Reserve Bank of St. Louis is titled “Why is inflation so low?” “The U.S. inflation rate has been below the Fed’s 2 percent inflation target since 2012,” the paper begins, going on to cite “several reasons to be concerned about very low inflation,” such as the risk of a recession caused by falling prices, or deflation. This isn’t a purely American phenomenon, either. The world has been trapped for years in a steady state of low price growth. In 2017, annual inflation across the rich countries that make up the Organization for Economic Cooperation and Development was just 1.7 percent.
Is this story about to change? Nobody knows. But one data point of 2.9 percent wage growth is just that: one point of data. It’s not proof that wages are taking off. It’s certainly not proof that accelerating wage growth is driving up prices. For now, it’s just a statistic, yet it seems to have helped trigger a frenzy of fear across global markets that inflation—that ever-feared and never-appeared boogeyman—will finally materialize.
For years, stock prices have inflated in part due to constraints on labor costs. Now at the slightest sign that labor costs might themselves be inflating, equities seem to be crashing for fear the central banks might rein in their support of economic growth. That’s quite a shame. If investors are wary of central bankers because they think bankers are wary of labor’s gains, it sets up a dynamic where capital specifically defines risk-free success by its capacity to restrain the prospects of labor. Capitalism may be the best flawed economic system out there, but is it any wonder that more Americans are starting to doubt that it’s working?", cover_img_url: "https://cdn.theatlantic.com/assets/media/img/mt/2018/02/AP_18040218154488/lead_960.jpg?1518189732")



Article.create(user_id: user1.id, title: "Netflix created a monster with its Cloverfield stunt, and Altered Carbon won’t be the last victim",
body: "This past weekend saw the release of a big, expensive, attention-getting science fiction spectacle on streaming service Netflix, one that had people talking throughout the subsequent week. Unfortunately for the people behind it, that spectacle wasn’t Altered Carbon.
Despite creating a 10-episode series whose visual design looks like it easily crossed over into the higher end of eight figures (guesstimates place it as arguably the costliest first season of television in history, comparable only to something like Game Of Thrones—not that Netflix is telling), the company derailed basically all the promotional steam the show had built up by unleashing the surprise reveal of The Cloverfield Paradox during the Super Bowl. And while the stunt worked, in the sense of Netflix’s brand getting another big shot of publicity right in the media-attention arm, it also pointed out the true problem with the Netflix model of constant content production. It could only call attention to its sci-fi movie at the expense of its sci-fi series—and at this point, some variant of that narrative is true across the board for nearly all of its properties. This is merely the most glaring example of a flawed business model that can’t see the forest for the trees. Netflix has poured truly staggering amounts of money into its programming, but is building a system where almost none of those shows and movies have room to thrive.
The reason is as simple as it is something Netflix wishes weren’t true: There’s only room for one big streaming release in the average media cycle. This is the same reason movie studios don’t release more than one film the same weekend: They don’t want to cost themselves money by forcing people to make a choice between two different movies, i.e. sources of revenue. In the case of a streaming service, the metrics are different, because Netflix arguably doesn’t care whether you’re watching Altered Carbon, The Cloverfield Paradox, or hell, even the godawful Rob Schneider series Real Rob, as long as you’re a paying subscriber. They want steady customers, and it doesn’t so much matter the reason new people sign up, as long as they keep doing it.", cover_img_url: "https://i.kinja-img.com/gawker-media/image/upload/s--FV-YUjWB--/c_scale,fl_progressive,q_80,w_1600/iloidugefjjwpyi1dfap.png")

Article.create(user_id: user1.id, title: "‘The Returned’ and ‘Ash vs Evil Dead’ Join ‘The Walking Dead’ in Offering High-Quality Horror",
body: "Halloween falls on a Saturday this year, which is traditionally the least-watched night for television. Perhaps this is fitting. In 2015, TV can be many things that are appropriate to the holiday: shocking, horrifying, sticky-sweet, overcommercialized, and deeply, deeply gross. But one thing it still struggles with is fear.1 Don’t believe me? Take a moment to consider: What’s the last regular TV show that was actually full-stop scary? I don’t mean frightful in bits and pieces, like one of Leatherface’s victims. I mean a show that is scary from top to bottom, from beginning to end. And I mean a show other than, say, Dads.
This isn’t a criticism so much as it’s a fact of life. Movies, with their contained running times, are especially good at sustaining mood. When you take your seat for a horror film, you’re essentially agreeing to be on the edge of it for 90 to 120 minutes. TV, by its very nature, demands a diversity of tone and pitch. Viewers simply can’t be asked to hold their breath for eight, 10, or even 22 hours a season. Try it and they’ll be dead even sooner than your show. Instead, TV traditionally has had to play in the margins of horror, building entire series out of the offcuts and scraps usually undervalued by the Fangoria crowd: the slow, agonizing buildup; the stolid, yeomanlike investigation; the long, sorrowful denouement. (Or, as is the case with Fox’s smarmy Scream Queens, the idea that a sneer can wound more deeply than a knife.) A scary movie is a turn through a haunted house. A scary TV show is more of a haunted time-share. There have to be at least occasional feints toward amenities like comfort and humor because, let’s be honest, you’re going to be there awhile.
If anyone were going to crack the horror code on TV, I would have expected it to be a pay service like HBO or Netflix, with their unlimited makeup budgets and freedom to micro-target audiences with the precision of a serial killer. But the two most successful series to challenge the primacy of scary cinema both hail from the diabolical Jigsaws in basic cable. FX’s American Horror Story, still slaying the ratings in its fifth iteration, is likely the closest TV has ever come to the specificity and sustained craziness of film. Part of this is due to the show’s creative casting and unquenchable thirst for extremity. But let’s be honest: The most noteworthy aspect of AHS isn’t the bearded lady, it’s the length of each season. By limiting each cycle to 13 hours and a single story, the show’s one, discordant note can ring out like a symphony. One doesn’t watch AHS so much as one commits to it.",
cover_img_url: "https://espngrantland.files.wordpress.com/2015/10/ashvsevildead-e1446070915528.jpg?w=750")

Article.create(user_id: user1.id, title: "The Ten Commandments", body: "You shall have no other gods before Me.
You shall not make idols.
You shall not take the name of the LORD your God in vain.
Remember the Sabbath day, to keep it holy.
Honor your father and your mother.
You shall not murder.
You shall not commit adultery.
You shall not steal.
You shall not bear false witness against your neighbor.
You shall not covet.", cover_img_url: "https://www.breakingisraelnews.com/wp-content/uploads/2016/06/10-ten-commandments-bible.jpg")

Article.create(user_id: user1.id, title: "How to stop doping in sports",
body: "PROFESSIONAL athletes pay a high price for their pursuit of excellence and glory. Training to the limit tears muscles and wears out joints. Gymnasts often need hip replacements when barely into middle age. Few footballers make it to the end of their careers with their knees intact.
But many also run a darker risk: doping. The Winter Olympics in Pyeongchang, in South Korea, starts this week in its shadow. Years after whistle-blowers first revealed wholesale doping in Russia, the International Olympic Committee (IOC) at last decided to bar it from taking part. But it has allowed many Russians to compete as individuals. And on the eve of the competition the Court of Arbitration for Sport said that 28 others should receive a more lenient penalty from the IOC, further muffling the anti-doping message.
Russia’s doping is unusual only in its scale and institutional nature. No country or sport is immune (see page 57). Studies, and an anonymous survey at the World Athletics Championships in 2011, suggest that a third of athletes preparing for big international competitions take banned substances. Yet just 1-2% fail a test each year. Lance Armstrong, a cyclist who won the Tour de France seven times and later admitted to doping all the while, was tested on 250 occasions. The few times he failed, he avoided sanctions by claiming he had taken anti-inflammatories for saddle-sores.
Doping is more sophisticated than when communist states used steroids to bulk up athletes. New drugs are designed to be undetectable in a blood or urine sample. Many athletes “blood dope”, receiving transfusions or taking a drug that stimulates the production of red blood cells to improve their stamina. Russian cheats “lost” test records in state-run labs and opened “tamper-proof” sample bottles with dental instruments.
Athletes who take banned substances put their health at risk. Soviet athletes who were fed steroids suffered a host of serious problems in later life. They were more likely to commit suicide, or to miscarry or have a disabled child. No one knows what risks those taking new “designer” versions are running. Blood-doping can cause heart attacks; more than a dozen cyclists’ deaths have been linked to it. Some unscrupulous coaches dope promising teenagers, before they are ever subjected to testing. The performance-enhancing benefits will last into their future careers. So will the damage.
The agencies that set out to stop doping are hugely outclassed. As the backtracking and bickering over sanctions on Russia illustrate, they are divided and weak. Most testing is done by national bodies, which may not try very hard to find evidence that would get their own stars banned. The World Anti-Doping Agency (WADA), which oversees them, is packed with officials from national sports federations and the IOC. Their interests are likewise conflicted. Its budget is tiny. The system seems to be designed to look tough but punish only the occasional scapegoat. Honest athletes deserve better.
Fixing doping means fixing incentives. WADA needs money, and to be independent of the sports officials who currently call the shots. Then it could improve testing and carry out more investigations—Russian doping was proved after whistle-blowers raised the alarm. “Athlete biological passports”, which monitor a range of markers in blood, show promise.
Above all, the punishment for doping should be severe and certain. No Russians should be competing in Pyeongchang after their country is known to have attempted wholesale fraud. Athletes should not have to choose between risking their health or being beaten by a cheat.", cover_img_url: "https://cdn.static-economist.com/sites/default/files/imagecache/640-width/images/print-edition/20180210_LDD002_0.jpg")

Article.create(user_id: user1.id, title: "Insider trading has been rife on Wall Street",
body: "Insider trading prosecutions have netted plenty of small fry. But many grumble that the big fish swim off unharmed. That nagging fear has some new academic backing, from three studies. One argues that well-connected insiders profited even from the financial crisis.
What is known about insider trading tends to come from prosecutions. But these require fortuitous tip-offs and extensive, expensive investigations, involving the examination of complex evidence from phone calls, e-mails or informants wired with recorders. The resulting haze of numbers may befuddle a jury unless they are leavened with a few spicy details—exotic code words, say, or (even better) suitcases filled with cash.
The papers make imaginative use of pattern analysis from data to find that insider trading is probably pervasive. The approach reflects a new way of analysing conduct in the financial markets. It also raises questions about how to treat behaviour if it is systemic rather than limited to the occasional rogue trader.
The first paper starts from the private meetings American government officials held during the crisis with financial institutions. Not made public at the time were critical details about what came to be called the Troubled Asset Relief Programme (TARP), notably how much money would be involved and how it would be allocated. This mattered hugely. The very survival of some institutions was at stake; in the end, hundreds of billions of dollars were pledged. Knowing the structure and scope of the bail-out in advance would have been a vitally important piece of information for investors during this period.
The paper examines conduct at 497 financial institutions between 2005 and 2011, paying particular attention to individuals who had previously worked in the federal government, in institutions including the Federal Reserve. In the two years prior to the TARP, these people’s trading gave no evidence of unusual insight. But in the nine months after the TARP was announced, they achieved particularly good results. The paper concludes that “politically connected insiders had a significant information advantage during the crisis and traded to exploit this advantage.”
The other papers use data from 1999 to 2014 from Abel Noser, a firm used by institutional investors to track trading transaction costs. The data covered 300 brokers but the papers focus on the 30 biggest, through which 80-85% of the trading volume flowed. They find evidence that large investors tend to trade more in periods ahead of important announcements, say, which is hard to explain unless they have access to unusually good information.
They could acquire such information in several ways. The most innocent is that brokers “spread the news” of a particular client’s desire to buy or sell large amounts of shares in order to create a market, much as an auction house might do for a painting. But it is also possible, the papers suggest, that they give this information to favoured clients to boost their own business. Strengthening this argument is the finding that large asset managers which use their own affiliated brokers do not lose out.
Large institutions can be both beneficiaries and victims of this sort of information leakage. But in general they are net gainers. The real losers, the papers conclude, are retail customers and smaller asset managers. Common to all the papers is the recognition that the public markets are, as conspiracy theorists have long argued, not truly public at all. Changing the law to fix that may not even be feasible. But at least, in large-scale data-crunching, a new type of corporate sleuth is on the case.", cover_img_url: "https://www.institutionalinvestor.com/Media/images/institutional-investor/2017-10-30/2017-12-Leanna-Orr-fea-Gay-on-Wall-St-webfeature1.jpg")
