# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Article.create(title: 'Fear not, China is not banning cryptocurrency', body: "In 2008 following the financial crisis, a paper titled “Bitcoin: A Peer-to-Peer Electronic Cash System” was published, detailing the concepts of a payment system. Bitcoin was born. Bitcoin gained the attention of the world for its use of blockchain technology and as an alternative to fiat currencies and commodities. Dubbed the next best technology after the internet, blockchain offered solutions to issues we have failed to address, or ignored over the past few decades. I will not delve into the technical aspect of it but here are some articles and videos that I recommend:

How Bitcoin Works Under the Hood

A gentle introduction to blockchain technology

Ever wonder how Bitcoin (and other cryptocurrencies) actually work?

Fast forward to today, 5th February to be exact, authorities in China have just unveiled a new set of regulations to ban cryptocurrency. The Chinese government have already done so last year, but many have circumvented through foreign exchanges. It has now enlisted the almighty ‘Great Firewall of China’ to block access to foreign exchanges in a bid to stop its citizens from carrying out any cryptocurrency transactions.

To know more about the Chinese government stance, let’s backtrack a couple years back to 2013 when Bitcoin was gaining popularity among the Chinese citizens and prices were soaring. Concerned with the price volatility and speculations, the People’s Bank of China and five other government ministries published an official notice on December 2013 titled “Notice on Preventing Financial Risk of Bitcoin” (Link is in Mandarin). Several points were highlighted:

1. Due to various factors such as limited supply, anonymity and lack of a centralized issuer, Bitcoin is not a official currency but a virtual commodity that cannot be used in the open market.

2. All banks and financial organizations are not allowed to offer Bitcoin-related financial services or engage in trading activity related to Bitcoin.

3. All companies and websites that offer Bitcoin-related services are to register with the necessary government ministries.

4. Due to the anonymity and cross-border features of Bitcoin, organizations providing Bitcoin-related services ought to implement preventive measures such as KYC to prevent money laundering. Any suspicious activity including fraud, gambling and money laundering should to be reported to the authorities.

5.Organizations providing Bitcoin-related services ought to educate the public about Bitcoin and the technology behind it and not mislead the public with misinformation.

In layman’s term, Bitcoin is categorized as a virtual commodity (e.g in-game credits,) that can be bought or sold in its original form and not to be exchanged with fiat currency. It cannot be defined as money- something that serves as a medium of exchange, a unit of accounting, and a store of value.

Despite the notice being dated in 2013, it is still relevant with regards to the Chinese government stance on Bitcoin and as mentioned, there is no indication of the banning Bitcoin and cryptocurrency. Rather, regulation and education about Bitcoin and blockchain will play a role in the Chinese crypto-market.

A similar notice was issued on Jan 2017, again emphasizing that Bitcoin is a virtual commodity and not a currency. In September 2017, the boom of initial coin offerings (ICOs) led to the publishing of a separate notice titled “Notice on Preventing Financial Risk of Issued Tokens”. Soon after, ICOs were banned and Chinese exchanges were investigated and eventually closed. (Hindsight is 20/20, they have made the right decision to ban ICOs and stop senseless gambling). Another blow was dealt to China’s cryptocurrency community in January 2018 when mining operations faced serious crackdowns, citing excessive electricity consumption." , cover_img_url: "https://blog.giantswarm.io/assets/2015/04/Wikimedia_Servers-small.jpg")

Article.create(title: "Are high US healthcare costs just an illusion?" , body: "Random Critical Analysis (or RCA, in honor of the dizzying array of acronyms the author there employs) has a blog post up in response to a recent New York Times article by Austin Frakt and Aaron Carroll in which they (Frakt and Carroll) reiterate the case famously made by Uwe Reinhardt that the astronomical costs of the US healthcare system can be attributed to the astronomically high prices found in the US healthcare system (rather than, say, higher utilization), which has always seemed a pretty straightforward and obvious case to me. RCA claims that this is wrong. The thrust of their (RCA’s) argument seems to be that, if you look at healthcare spending in relation to the average disposable household income of various countries, rather than, say, as a % of GDP, US spending is not out of line at all, and therefore there’s little to explain in the first place. This is not the only argument that RCA makes, but it underlies most of the post, and it’s the one I am going to address here, briefly. RCA’s full post is very thoroughly written, very interesting, and well worth reading (as are the previous posts that it summarizes and links back to).
RCA claims that using real household disposable income is the proper way to put US healthcare spending in context, for two reasons. First, it is an incredibly accurate predictor for how much per capita health expenditure there will be in any given country. Second, it most reflects how people would intuitively think about healthcare spending as “domestic opportunity cost (i.e., how much real consumption is foregone when buying a comparable bundle of health care in a given country as compared to the OECD average)”.
RCA provides plenty of statistical evidence that the first aspect of the household disposable income variable is very true, i.e. it is a great predictor of healthcare expenditures. First I will give you their slick graph demonstrating this, and then I will show you my terrible graph, just as evidence that I was able to track down the data and methodology that they use for each axis here (and that task proved difficult for some of their other graphs), as I will later expand on that data.
As you can see, our graphs are basically the same, other than one being clearly labeled and nice to look at, and the other one not like that at all. There are a few other differences. RCA used 2010 dollars, while I use 2014 data in 2014 dollars, and maybe we somehow ended up with a different country or two included in our respective datasets. But it is basically the same, and demonstrates the same thing. Per capita disposable household income is a great predictor of a country’s per capita healthcare spending level. And when we look at things like this, the US is right in line.
The second aspect of thinking about this variable is, beyond its predictive power, what does it really tell us? Again, RCA claims that this is a good way to measure relative costs because, if I understand their argument correctly, if I have a lot of disposable income, then of course I’m going to spend more freely on healthcare. This makes sense of course, taken as an assertion of its own. However, as justification for using the per capita disposable household income variable, it falls short. The primary reason that it does is because per capita means average, and in any given country, income may be distributed radically unequally. Thus, the average American household might see little meaningful loss of consumption opportunity when buying healthcare, but this doesn’t preclude the possibility that even the vast majority of Americans might see a lot of lost opportunity.
We can step back now and ask what it means that there’s such a strong correlation between healthcare cost and per capita disposable household income. Well, if we want to take it to the very extreme, it could be that the healthcare industry is very profitable for the upper income brackets in certain countries and that there is every incentive to keep it this way. Since having a lot of money generally translates to having political power, or so we all assume, there is, beyond the desire, the actual means to keep healthcare costs high. Add in massive income inequality, and you have a correlation that (in this extreme speculative way of thinking) just tells you that in some countries, people are allowed to get rich off of healthcare and they follow that to the logical, market economy conclusion. To be clear, I am not saying that this all is definitely why we see a strong correlation between per capita disposable income and overall healthcare costs. I am saying that “Everybody in the country is equally well-off and so doesn’t mind that a stay in the hospital in their country costs as much as a house in another country,” is not an obviously correct assumption to make about why that correlation between per capita disposable income and healthcare expenditures exists.
While I can’t resolve this all, what I can do is offer a clearer picture of how these costs are actually felt by people in a given country, beyond a per capita measure. To do this, I start with the same graph as above, and the same data that it’s based on. But I add an extra layer to it, the Gini index, which is a common measure of domestic inequality. Specifically, I take the per capita household disposable income number, and divide it by the World Bank Gini score (on a scale of 1–100, where 1 means perfect equality, and 100 means perfect inequality.) In order to bring things back to scale, I multiply this by the average Gini score for all of the countries in the analysis. Now we have a really adjusted measure of per capita household disposable income, i.e., one that means something in the context of real people.
First, to demonstrate that this isn’t a very stupid idea, let’s look at the predictive power of using this as a variable. Here is a regression on per capita healthcare costs by the Gini-adjusted income measure, excluding the U.S.“ , cover_img_url: "https://www.statnews.com/wp-content/uploads/2017/12/Blockchain-healthcare-graphic-645x645.png")
